# Default values for dev-spaces
# Portable Helm chart - works with or without ACM

devspaces:
  name: devspaces
  namespace: openshift-operators-redhat
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
