# Default values for the autoshift
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
autoshift: 
  appName: "autoshift"
  repoUrl: "https://github.com/auto-shift/autoshiftv2.git"
  valuesFile: "values.hubofhubs.yaml"
  argoProject: "default"
  gitopsNamespace: "openshift-gitops"
