# Default values for tempo
policy_namespace: open-cluster-policies

tempo:
  name: tempo-product
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
