clustergroup:
  clusterGroup:
    name: hub

    namespaces:
      - open-cluster-management

    subscriptions:
      openshift-gitops:
        name: openshift-gitops-operator
        namespace: openshift-operators
        channel: gitops-1.19        # Match autoshift/values/clustersets/hub.yaml
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      acm:
        name: advanced-cluster-management
        namespace: open-cluster-management
        channel: release-2.15       # Match autoshift/values/clustersets/hub.yaml
        source: redhat-operators
        sourceNamespace: openshift-marketplace

    applications:
      autoshift:
        name: autoshift
        namespace: openshift-gitops
        path: autoshift
        extraValueFiles:
          - /autoshift/values/global.yaml
          - /autoshift/values/clustersets/hub.yaml
          - /autoshift/values/clustersets/managed.yaml
