clusterGroup:
  name: hub

  namespaces:
    open-cluster-management:

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.15       # Match autoshift/values/clustersets/hub.yaml
      source: redhat-operators
      sourceNamespace: openshift-marketplace

  applications:
    autoshift:
      name: autoshift
      namespace: autoshift-hub
      path: autoshift
      overrides:
        - name: gitopsNamespace
          value: autoshift-hub
        - name: gitops.argoName
          value: hub-gitops
        - name: gitops.argoNamespace
          value: autoshift-hub
      extraValueFiles:
        - /autoshift/values/global.yaml
        - /autoshift/values/clustersets/hub.yaml
        - /autoshift/values/clustersets/managed.yaml

  extraObjects:
    multiclusterhub:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: open-cluster-management
        annotations:
          argocd.argoproj.io/sync-wave: "1"
      spec:
        availabilityConfig: High
