clusterGroup:
  name: hub

  namespaces:
    open-cluster-management:

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.15       # Match autoshift/values/clustersets/hub.yaml
      source: redhat-operators
      sourceNamespace: openshift-marketplace

  applications:
    autoshift:
      name: autoshift
      path: autoshift
      syncPolicy: Automatic
      extraValueFiles:
        - /autoshift/values/global.yaml
        - /autoshift/values/clustersets/hub.yaml
        - /autoshift/values/clustersets/hub-pattern.yaml
        - /autoshift/values/clustersets/managed.yaml

  extraObjects:
    multiclusterhub:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: open-cluster-management
        annotations:
          argocd.argoproj.io/sync-wave: "1"
          argocd.argoproj.io/sync-options: Prune=false
      spec:
        availabilityConfig: High
