# Default values for openshift-pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
pipelines:
    name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: pipelines-1.21
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# pipelines<bool>: 'true' or 'false' - Enable OpenShift Pipelines (Tekton)
#
# Configuration:
# pipelines-channel<String>: Operator channel (default: 'pipelines-1.21')
# pipelines-version<String>: Specific operator version (CSV) to install (optional)
# pipelines-source<String>: Operator catalog source (default: 'redhat-operators')
# pipelines-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/pipelines: 'true'
# autoshift.io/pipelines-channel: 'pipelines-1.21'
# autoshift.io/pipelines-version: 'openshift-pipelines-operator-rh.v1.18.1'