# Default values for tempo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
tempo:
  name: tempo-product
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: global-operators
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - openshift-operators
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# tempo<bool>: 'true' or 'false' - Controls whether tempo is managed
#
# Configuration:
# tempo-subscription-name<string>: Operator subscription name (default: 'tempo-product')
# tempo-channel<string>: Operator channel (default: 'stable')
# tempo-version<string>: Specific operator version (CSV) to install (optional)
# tempo-source<string>: Operator catalog source (default: 'redhat-operators')
# tempo-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/tempo: 'true'
# autoshift.io/tempo-subscription-name: 'tempo-product'
# autoshift.io/tempo-channel: 'stable'
# autoshift.io/tempo-version: 'operator-name.v1.x.x'
# autoshift.io/tempo-source: 'redhat-operators'
# autoshift.io/tempo-source-namespace: 'openshift-marketplace'