# Values with hub template overrides for per-cluster configuration
policy_namespace: ${POLICY_NAMESPACE}

tempo:
  name: tempo-product
  namespace: openshift-operators
  channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/tempo-channel" | default "stable" {{ "hub}}" }}'
  source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/tempo-source" | default "redhat-operators" {{ "hub}}" }}'
  sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/tempo-source-namespace" | default "openshift-marketplace" {{ "hub}}" }}'
