# Default values for dynatrace
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
dynatrace:
  name: dynatrace-operator
  namespace: dynatrace
  channel: alpha
  source: certified-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: dynatrace-operator-group
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - dynatrace
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# dynatrace<bool>: 'true' or 'false' - Controls whether dynatrace is managed
#
# Configuration:
# dynatrace-subscription-name<string>: Operator subscription name (default: 'dynatrace-operator')
# dynatrace-channel<string>: Operator channel (default: 'alpha')
# dynatrace-version<string>: Specific operator version (CSV) to install (optional)
# dynatrace-source<string>: Operator catalog source (default: 'redhat-operators')
# dynatrace-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/dynatrace: 'true'
# autoshift.io/dynatrace-subscription-name: 'dynatrace-operator'
# autoshift.io/dynatrace-channel: 'alpha'
# autoshift.io/dynatrace-version: 'operator-name.v1.x.x'
# autoshift.io/dynatrace-source: 'redhat-operators'
# autoshift.io/dynatrace-source-namespace: 'openshift-marketplace'