# Default values for kiali
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
kiali:
  name: kiali-ossm
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: global-operators
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - openshift-operators
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# kiali<bool>: 'true' or 'false' - Controls whether kiali is managed
#
# Configuration:
# kiali-subscription-name<string>: Operator subscription name (default: 'kiali-ossm')
# kiali-channel<string>: Operator channel (default: 'stable')
# kiali-version<string>: Specific operator version (CSV) to install (optional)
# kiali-source<string>: Operator catalog source (default: 'redhat-operators')
# kiali-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/kiali: 'true'
# autoshift.io/kiali-subscription-name: 'kiali-ossm'
# autoshift.io/kiali-channel: 'stable'
# autoshift.io/kiali-version: 'operator-name.v1.x.x'
# autoshift.io/kiali-source: 'redhat-operators'
# autoshift.io/kiali-source-namespace: 'openshift-marketplace'