apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-create-rhbk-configmap
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "4"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    {{- if not .Values.ignoreHelmHooks }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-rhbk-configmap
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # Create namespace exists
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.namespace }}
            # ConfigMap for CA certificate
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: {{ .Values.namespace }}-ca-cm
                  namespace: openshift-config
                data:
                  ca.crt: |-
                {{- (.Files.Get .Values.idp.cafile) | nindent 20 }}
    {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-create-rhbk-configmap
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}

  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/rhbk-idp'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-policy-create-rhbk-configmap
  namespace: {{ .Values.policy_namespace }}
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-create-rhbk-configmap
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-create-rhbk-configmap

