# Default values for rhoai
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
rhoai:
  name: rhods-operator
  namespace: redhat-ods-operator
  channel: fast
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: rhoai-operator-group
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - redhat-ods-operator
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# rhoai<bool>: 'true' or 'false' - Controls whether rhoai is managed
#
# Configuration:
# rhoai-subscription-name<string>: Operator subscription name (default: 'rhods-operator')
# rhoai-channel<string>: Operator channel (default: 'fast')
# rhoai-version<string>: Specific operator version (CSV) to install (optional)
# rhoai-source<string>: Operator catalog source (default: 'redhat-operators')
# rhoai-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/rhoai: 'true'
# autoshift.io/rhoai-subscription-name: 'rhods-operator'
# autoshift.io/rhoai-channel: 'fast'
# autoshift.io/rhoai-version: 'operator-name.v1.x.x'
# autoshift.io/rhoai-source: 'redhat-operators'
# autoshift.io/rhoai-source-namespace: 'openshift-marketplace'