# Default values for node-feature-discovery
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
nodeFeatureDiscovery:
  name: nfd
  namespace: openshift-nfd
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: openshift-nfd-operator
  targetNamespaces: # Target namespaces for namespace-scoped operators
    - openshift-nfd
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# node-feature-discovery<bool>: 'true' or 'false' - Controls whether node-feature-discovery is managed
#
# Configuration:
# node-feature-discovery-subscription-name<string>: Operator subscription name (default: 'nfd')
# node-feature-discovery-channel<string>: Operator channel (default: 'stable')
# node-feature-discovery-version<string>: Specific operator version (CSV) to install (optional)
# node-feature-discovery-source<string>: Operator catalog source (default: 'redhat-operators')
# node-feature-discovery-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/node-feature-discovery: 'true'
# autoshift.io/node-feature-discovery-subscription-name: 'nfd'
# autoshift.io/node-feature-discovery-channel: 'stable'
# autoshift.io/node-feature-discovery-version: 'operator-name.v1.x.x'
# autoshift.io/node-feature-discovery-source: 'redhat-operators'
# autoshift.io/node-feature-discovery-source-namespace: 'openshift-marketplace'