# Default values for vault-secrets
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
vaultSecrets:
  name: vault-secrets-operator
  namespace: openshift-operators
  channel: stable
  source: certified-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: global-operators
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - openshift-operators


# To deploy the policy using the Vault secret creation example in templates,
# add this block to the values.yaml file of the Operator Policy chart that requires secrets.
vault:
  connectionAddress:          # The URL of your Vault server
  mount:        # Name of your secrets engine
  path:         # Name of the secret in that engine
  authMountName:        # Name of your auth method
  secretName:         # Name of the secret in your OpenShift namespace
  roleID:         # Role ID of your AppRole in Vault
  secretRef:        # Name of secret containing your Secret ID that exists in the policies-autoshift namespace on the hub

# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# vault-secrets<bool>: 'true' or 'false' - Controls whether vault-secrets is managed
#
# Configuration:
# vault-secrets-subscription-name<string>: Operator subscription name (default: 'vault-secrets-operator')
# vault-secrets-channel<string>: Operator channel (default: 'stable')
# vault-secrets-version<string>: Specific operator version (CSV) to install (optional)
# vault-secrets-source<string>: Operator catalog source (default: 'redhat-operators')
# vault-secrets-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/vault-secrets: 'true'
# autoshift.io/vault-secrets-subscription-name: 'vault-secrets-operator'
# autoshift.io/vault-secrets-channel: 'stable'
# autoshift.io/vault-secrets-version: 'operator-name.v1.x.x'
# autoshift.io/vault-secrets-source: 'redhat-operators'
# autoshift.io/vault-secrets-source-namespace: 'openshift-marketplace'