# Default values for openshift-pipelines capabilities
# This is a YAML-formatted file.

policy_namespace: open-cluster-policies

pipelines:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  channel: pipelines-1.20
  source: redhat-operators
  sourceNamespace: openshift-marketplace
