# autoshift-idp/values.yaml
policy_namespace: policies-autoshift
namespace: openshift-rhbk-idp
image: dcregistry.example.priv:8443/applications/ose-cli:latest

openshift:
  clustername: ocpacm
  basedomain: example.priv

# Keycloak Configuration
keycloak:
  name: openshift-rhbk
  hostname: openshift-rhbk.apps.ocpacm.example.priv

# Realm Configuration
realm:
  name: "autoshift"

# OpenShift OAuth Configuration
idp:
  name: "rhbk-idp"
  clientID: "rhbk-autoshift-client"
  clientSecret: "krahYBwk0vikKoy3YnLdCSXVgzaUfONt"
  issuerURL: "https://openshift-rhbk.apps.ocpacm.example.priv/realms/autoshift"
  redirectUris: "https://oauth-openshift.apps.ocpacm.example.priv/*"
  cafile: "files/ca.crt"

