# Default values for lvm capabilities
policy_namespace: open-cluster-policies

lvm:
  default: 'true'
  fstype: xfs
  sizePercent: 90
  overprovisionRatio: 10
  name: lvms-operator
  namespace: openshift-storage
  channel: stable-4.18
  source: redhat-operators
  sourceNamespace: openshift-marketplace
