apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-machineconfigs
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  disabled: false
  dependencies:
    - name: policy-trident-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-trident-machine-configs
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{- range $role := list "master" "worker" }}
            - complianceType: musthave
              objectDefinition:
                kind: MachineConfig
                apiVersion: machineconfiguration.openshift.io/v1
                metadata:
                  name: 99-{{ $role }}-ensure-proper-nqn
                  labels:
                    machineconfiguration.openshift.io/role: {{ $role }}
                spec:
                  config:
                    ignition:
                      version: 3.2.0
                    systemd:
                      units:
                        - name: ensure-proper-nqn.service
                          enabled: true
                          contents: |
                            [Unit]
                            Description=ensure proper NQN
                            Before=network.target

                            [Service]
                            ExecStart=/usr/bin/sh -c 'HOSTNAME=$(hostname); echo "nqn.2024-05.io.openshift:$HOSTNAME" > /etc/nvme/hostnqn'
                            RemainAfterExit=yes

                            [Install]
                            WantedBy=multi-user.target
            {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: enable-nvme-tcp-module
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{- range $role := list "master" "worker" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  name: 99-{{ $role }}-enable-nvme-tcp-module
                  labels:
                    machineconfiguration.openshift.io/role: {{ $role }}
                spec:
                  config:
                    ignition:
                      version: 3.4.0
                    storage:
                      files:
                        - path: /etc/modules-load.d/nvme-tcp.conf
                          mode: 420
                          overwrite: true
                          contents:
                            compression: ""
                            source: data:,nvme-tcp
            {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-machineconfigs
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
                - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-machineconfigs
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-machineconfigs
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-machineconfigs
    apiGroup: policy.open-cluster-management.io
    kind: Policy