{{- if (.Files.Glob "files/**") }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-storage-configuration
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-trident-configmaps
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
    - name: policy-trident-orchestrator
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-storage-configuration
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub-" }} $tridentconfig_list := list {{ "hub}}" }}
            {{ "{{hub-" }} range $label, $labelvalue := .ManagedClusterLabels {{ "hub}}" }}
              {{ "{{hub-" }} if $label | hasPrefix "autoshift.io/trident-config-" {{ "hub}}" }}
                {{ "{{hub-" }} $tridentconfig_list = append $tridentconfig_list $labelvalue {{ "hub}}" }}
              {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} range $tridentconfig_list {{ "hub}}" }}
              {{ "{{hub-" }} $cfg := ((lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (print "trident-" .)).data) {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                {{ "{{hub-" }} if $cfg.adv {{ "hub}}" }}
                    {{ "{{hub " }} $cfg.adv | base64dec | autoindent {{ "hub}}" }}
                  {{ "{{hub-" }} end {{ "hub}}" }}
                {{ "{{hub-" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-storage-configuration
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-storage-configuration
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-storage-configuration
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-storage-configuration
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end }}
