{{- if (.Files.Glob "files/**") }}
{{- $files := .Files.Glob "files/**" }}
{{- if $files }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-configmaps
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-trident-orchestrator
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: trident-configmap
          namespace: {{ .Values.policy_namespace }}
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            {{- range $path, $_ := $files }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: trident-{{ ($path | trimPrefix "files/" | split ".")._0 }}
                  namespace: {{ $.Values.policy_namespace }}
                data:
                  adv: {{ $.Files.Get $path | b64enc }}
            {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-trident-configmap
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-trident-configmap
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-trident-configmap
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-configmaps
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end }}
{{- end }}
