---
# Template file - variables substituted by CMP before kustomize runs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${POLICY_NAMESPACE}

generators:
  - policy-generator.yaml

resources:
  - placement.yaml
