# Default values for serverless
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
serverless:
  name: serverless-operator
  namespace: openshift-serverless
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: serverless-operator-group
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - openshift-serverless
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# serverless<bool>: 'true' or 'false' - Controls whether serverless is managed
#
# Configuration:
# serverless-subscription-name<string>: Operator subscription name (default: 'serverless-operator')
# serverless-channel<string>: Operator channel (default: 'stable')
# serverless-version<string>: Specific operator version (CSV) to install (optional)
# serverless-source<string>: Operator catalog source (default: 'redhat-operators')
# serverless-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/serverless: 'true'
# autoshift.io/serverless-subscription-name: 'serverless-operator'
# autoshift.io/serverless-channel: 'stable'
# autoshift.io/serverless-version: 'operator-name.v1.x.x'
# autoshift.io/serverless-source: 'redhat-operators'
# autoshift.io/serverless-source-namespace: 'openshift-marketplace'