# Default values for openshift-virtualization
# Portable Helm chart - works with or without ACM

virt:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
