# Default values for openshift-virtualization.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
mtv:
  name: mtv-operator
  namespace: openshift-mtv
  channel: release-v2.9
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
