# Default values for node-feature-discovery
# Portable Helm chart - works with or without ACM

nodeFeatureDiscovery:
  name: nfd
  namespace: openshift-nfd
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: openshift-nfd-operator
  targetNamespaces:
    - openshift-nfd
