# Values with hub template overrides for per-cluster configuration
policy_namespace: ${POLICY_NAMESPACE}

logging:
  name: cluster-logging
  namespace: openshift-logging
  channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-channel" | default "stable-6.4" {{ "hub}}" }}'
  source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-source" | default "redhat-operators" {{ "hub}}" }}'
  sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-source-namespace" | default "openshift-marketplace" {{ "hub}}" }}'
