# Default values for logging
policy_namespace: open-cluster-policies

logging:
  name: cluster-logging
  namespace: openshift-logging
  channel: stable-6.4
  source: redhat-operators
  sourceNamespace: openshift-marketplace
