# Default values for developer-hub
# Portable Helm chart - works with or without ACM

developerHub:
  name: rhdh
  namespace: rhdh-operator
  channel: fast-1.8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
