# Default values for openshift-compliance-operator
# Portable Helm chart - works with or without ACM

compliance:
  name: compliance-operator
  namespace: openshift-compliance
  nameSub: compliance-operator
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
