# Default values for kiali
# Portable Helm chart - works with or without ACM

kiali:
  name: kiali-ossm
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
