# Default values for autoshift-pipeline
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies

# Pipeline configuration
pipeline:
  namespace: autoshift-pipeline
  serviceAccount: autoshift-pipeline

# Git repository configuration
git:
  repo: https://github.com/auto-shift/autoshiftv2.git
  branch: main

# ArgoCD configuration
argocd:
  namespace: openshift-gitops
  application:
    name: autoshift
    project: default


# Webhook configuration
webhook:
  secretName: git-webhook-token
  secretKey: token

# Container images
images:
  cli: registry.redhat.io/openshift4/ose-cli:latest

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# hubClusterSets:
#   hub:
#     labels:
#       autoshift-pipeline: 'true'
# managedClusterSets:
#   managed:
#     labels:
#       autoshift-pipeline: 'false'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# autoshift-pipeline<bool>: 'true' or 'false' - Enable AutoShift Pipeline deployment
#
# Configuration:
# autoshift-pipeline-webhook-secret<String>: Name of webhook secret
# autoshift-pipeline-cli-image<String>: CLI container image for disconnected environments
#
# Examples:
# autoshift.io/autoshift-pipeline: 'true'
# autoshift.io/autoshift-pipeline-cli-image: 'registry.internal.mil/openshift4/ose-cli:v4.18'